// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: server/user-pb/user.proto

package user_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePic    string                 `protobuf:"bytes,3,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	Validated     bool                   `protobuf:"varint,4,opt,name=validated,proto3" json:"validated,omitempty"`
	Admin         bool                   `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
	SuperAdmin    bool                   `protobuf:"varint,6,opt,name=super_admin,json=superAdmin,proto3" json:"super_admin,omitempty"`
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	CodeExpire    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=code_expire,json=codeExpire,proto3" json:"code_expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

func (x *UserRequest) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *UserRequest) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *UserRequest) GetSuperAdmin() bool {
	if x != nil {
		return x.SuperAdmin
	}
	return false
}

func (x *UserRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserRequest) GetCodeExpire() *timestamppb.Timestamp {
	if x != nil {
		return x.CodeExpire
	}
	return nil
}

type UserLoginRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Email                  string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Browser                string                 `protobuf:"bytes,2,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion         string                 `protobuf:"bytes,3,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	OperatingSystem        string                 `protobuf:"bytes,4,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	OperatingSystemVersion string                 `protobuf:"bytes,5,opt,name=operating_system_version,json=operatingSystemVersion,proto3" json:"operating_system_version,omitempty"`
	Cpu                    string                 `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Language               string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Timezone               string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CookiesEnabled         bool                   `protobuf:"varint,9,opt,name=cookies_enabled,json=cookiesEnabled,proto3" json:"cookies_enabled,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *UserLoginRequest) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *UserLoginRequest) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *UserLoginRequest) GetOperatingSystemVersion() string {
	if x != nil {
		return x.OperatingSystemVersion
	}
	return ""
}

func (x *UserLoginRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *UserLoginRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserLoginRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserLoginRequest) GetCookiesEnabled() bool {
	if x != nil {
		return x.CookiesEnabled
	}
	return false
}

type UserMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMailRequest) Reset() {
	*x = UserMailRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMailRequest) ProtoMessage() {}

func (x *UserMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMailRequest.ProtoReflect.Descriptor instead.
func (*UserMailRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserMailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserTokenRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Token                  string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Browser                string                 `protobuf:"bytes,2,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion         string                 `protobuf:"bytes,3,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	OperatingSystem        string                 `protobuf:"bytes,4,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	OperatingSystemVersion string                 `protobuf:"bytes,5,opt,name=operating_system_version,json=operatingSystemVersion,proto3" json:"operating_system_version,omitempty"`
	Cpu                    string                 `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Language               string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Timezone               string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CookiesEnabled         bool                   `protobuf:"varint,9,opt,name=cookies_enabled,json=cookiesEnabled,proto3" json:"cookies_enabled,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserTokenRequest) Reset() {
	*x = UserTokenRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTokenRequest) ProtoMessage() {}

func (x *UserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTokenRequest.ProtoReflect.Descriptor instead.
func (*UserTokenRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserTokenRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *UserTokenRequest) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *UserTokenRequest) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *UserTokenRequest) GetOperatingSystemVersion() string {
	if x != nil {
		return x.OperatingSystemVersion
	}
	return ""
}

func (x *UserTokenRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *UserTokenRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserTokenRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserTokenRequest) GetCookiesEnabled() bool {
	if x != nil {
		return x.CookiesEnabled
	}
	return false
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserIDRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Permanently   bool                   `protobuf:"varint,2,opt,name=permanently,proto3" json:"permanently,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserDeleteRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDeleteRequest) GetPermanently() bool {
	if x != nil {
		return x.Permanently
	}
	return false
}

type UserUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePic    string                 `protobuf:"bytes,3,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserUpdateRequest) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

func (x *UserUpdateRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type UserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDResponse) Reset() {
	*x = UserIDResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDResponse) ProtoMessage() {}

func (x *UserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDResponse.ProtoReflect.Descriptor instead.
func (*UserIDResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserIDResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserIDResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusResponse) Reset() {
	*x = UserStatusResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusResponse) ProtoMessage() {}

func (x *UserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusResponse.ProtoReflect.Descriptor instead.
func (*UserStatusResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserStatusResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResponse        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsersResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePic    string                 `protobuf:"bytes,3,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	Validated     bool                   `protobuf:"varint,4,opt,name=validated,proto3" json:"validated,omitempty"`
	Admin         bool                   `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
	SuperAdmin    bool                   `protobuf:"varint,6,opt,name=super_admin,json=superAdmin,proto3" json:"super_admin,omitempty"`
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	CodeExpire    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=code_expire,json=codeExpire,proto3" json:"code_expire,omitempty"`
	Bucket        string                 `protobuf:"bytes,9,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Id            uint64                 `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	PhoneE164     string                 `protobuf:"bytes,11,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

func (x *UserResponse) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *UserResponse) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *UserResponse) GetSuperAdmin() bool {
	if x != nil {
		return x.SuperAdmin
	}
	return false
}

func (x *UserResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserResponse) GetCodeExpire() *timestamppb.Timestamp {
	if x != nil {
		return x.CodeExpire
	}
	return nil
}

func (x *UserResponse) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *UserResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

type UserValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserValidateRequest) Reset() {
	*x = UserValidateRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserValidateRequest) ProtoMessage() {}

func (x *UserValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserValidateRequest.ProtoReflect.Descriptor instead.
func (*UserValidateRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserValidateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserLoginResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserLoginResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserTokenResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Email               string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token               string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Status              uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	TokenRefresh        string                 `protobuf:"bytes,4,opt,name=token_refresh,json=tokenRefresh,proto3" json:"token_refresh,omitempty"`
	TokenRefreshExpires *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=token_refresh_expires,json=tokenRefreshExpires,proto3" json:"token_refresh_expires,omitempty"`
	TokenExpires        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=token_expires,json=tokenExpires,proto3" json:"token_expires,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserTokenResponse) Reset() {
	*x = UserTokenResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTokenResponse) ProtoMessage() {}

func (x *UserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTokenResponse.ProtoReflect.Descriptor instead.
func (*UserTokenResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{13}
}

func (x *UserTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserTokenResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserTokenResponse) GetTokenRefresh() string {
	if x != nil {
		return x.TokenRefresh
	}
	return ""
}

func (x *UserTokenResponse) GetTokenRefreshExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenRefreshExpires
	}
	return nil
}

func (x *UserTokenResponse) GetTokenExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenExpires
	}
	return nil
}

type UpdateUserAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Admin         bool                   `protobuf:"varint,2,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAdminRequest) Reset() {
	*x = UpdateUserAdminRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAdminRequest) ProtoMessage() {}

func (x *UpdateUserAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAdminRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserAdminRequest) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type UserLoginWithPasswordRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Email                  string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password               string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Browser                string                 `protobuf:"bytes,3,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion         string                 `protobuf:"bytes,4,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	OperatingSystem        string                 `protobuf:"bytes,5,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	OperatingSystemVersion string                 `protobuf:"bytes,6,opt,name=operating_system_version,json=operatingSystemVersion,proto3" json:"operating_system_version,omitempty"`
	Cpu                    string                 `protobuf:"bytes,7,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Language               string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	Timezone               string                 `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CookiesEnabled         bool                   `protobuf:"varint,10,opt,name=cookies_enabled,json=cookiesEnabled,proto3" json:"cookies_enabled,omitempty"`
	PhoneE164              string                 `protobuf:"bytes,11,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserLoginWithPasswordRequest) Reset() {
	*x = UserLoginWithPasswordRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginWithPasswordRequest) ProtoMessage() {}

func (x *UserLoginWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*UserLoginWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserLoginWithPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetOperatingSystemVersion() string {
	if x != nil {
		return x.OperatingSystemVersion
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserLoginWithPasswordRequest) GetCookiesEnabled() bool {
	if x != nil {
		return x.CookiesEnabled
	}
	return false
}

func (x *UserLoginWithPasswordRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

type UserRegisterWithPasswordRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Email                  string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password               string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Browser                string                 `protobuf:"bytes,4,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion         string                 `protobuf:"bytes,5,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	OperatingSystem        string                 `protobuf:"bytes,6,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	OperatingSystemVersion string                 `protobuf:"bytes,7,opt,name=operating_system_version,json=operatingSystemVersion,proto3" json:"operating_system_version,omitempty"`
	Cpu                    string                 `protobuf:"bytes,8,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Language               string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	Timezone               string                 `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CookiesEnabled         bool                   `protobuf:"varint,11,opt,name=cookies_enabled,json=cookiesEnabled,proto3" json:"cookies_enabled,omitempty"`
	PhoneE164              string                 `protobuf:"bytes,12,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserRegisterWithPasswordRequest) Reset() {
	*x = UserRegisterWithPasswordRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterWithPasswordRequest) ProtoMessage() {}

func (x *UserRegisterWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*UserRegisterWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserRegisterWithPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetOperatingSystemVersion() string {
	if x != nil {
		return x.OperatingSystemVersion
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserRegisterWithPasswordRequest) GetCookiesEnabled() bool {
	if x != nil {
		return x.CookiesEnabled
	}
	return false
}

func (x *UserRegisterWithPasswordRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

// verification_code crosses a trusted internal gRPC boundary so a consuming
// backend can deliver it. Public browser-facing APIs must not echo it.
type UserRegisterWithPasswordResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	CodeExpires      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=code_expires,json=codeExpires,proto3" json:"code_expires,omitempty"`
	Status           uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserRegisterWithPasswordResponse) Reset() {
	*x = UserRegisterWithPasswordResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterWithPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterWithPasswordResponse) ProtoMessage() {}

func (x *UserRegisterWithPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterWithPasswordResponse.ProtoReflect.Descriptor instead.
func (*UserRegisterWithPasswordResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{17}
}

func (x *UserRegisterWithPasswordResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRegisterWithPasswordResponse) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *UserRegisterWithPasswordResponse) GetCodeExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.CodeExpires
	}
	return nil
}

func (x *UserRegisterWithPasswordResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserRequestPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequestPasswordResetRequest) Reset() {
	*x = UserRequestPasswordResetRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequestPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequestPasswordResetRequest) ProtoMessage() {}

func (x *UserRequestPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequestPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*UserRequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{18}
}

func (x *UserRequestPasswordResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// reset_token crosses a trusted internal gRPC boundary for email delivery.
// Public browser-facing APIs must always return a generic accepted response.
type UserRequestPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetToken    string                 `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Status        uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequestPasswordResetResponse) Reset() {
	*x = UserRequestPasswordResetResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequestPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequestPasswordResetResponse) ProtoMessage() {}

func (x *UserRequestPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequestPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*UserRequestPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{19}
}

func (x *UserRequestPasswordResetResponse) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

func (x *UserRequestPasswordResetResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *UserRequestPasswordResetResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetToken    string                 `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResetPasswordRequest) Reset() {
	*x = UserResetPasswordRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResetPasswordRequest) ProtoMessage() {}

func (x *UserResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*UserResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{20}
}

func (x *UserResetPasswordRequest) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

func (x *UserResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UserResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResetPasswordResponse) Reset() {
	*x = UserResetPasswordResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResetPasswordResponse) ProtoMessage() {}

func (x *UserResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*UserResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{21}
}

func (x *UserResetPasswordResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserSetPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *UserTokenRequest      `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	PhoneE164     string                 `protobuf:"bytes,2,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSetPhoneRequest) Reset() {
	*x = UserSetPhoneRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSetPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSetPhoneRequest) ProtoMessage() {}

func (x *UserSetPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSetPhoneRequest.ProtoReflect.Descriptor instead.
func (*UserSetPhoneRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{22}
}

func (x *UserSetPhoneRequest) GetAuth() *UserTokenRequest {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *UserSetPhoneRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

type UserChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Auth            *UserTokenRequest      `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserChangePasswordRequest) Reset() {
	*x = UserChangePasswordRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChangePasswordRequest) ProtoMessage() {}

func (x *UserChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*UserChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{23}
}

func (x *UserChangePasswordRequest) GetAuth() *UserTokenRequest {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *UserChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *UserChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// verification_code crosses only the trusted internal gRPC boundary for the
// existing verification email publisher; browser-facing APIs must not echo it.
type UserChangeEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *UserTokenRequest      `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserChangeEmailRequest) Reset() {
	*x = UserChangeEmailRequest{}
	mi := &file_server_user_pb_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChangeEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChangeEmailRequest) ProtoMessage() {}

func (x *UserChangeEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChangeEmailRequest.ProtoReflect.Descriptor instead.
func (*UserChangeEmailRequest) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{24}
}

func (x *UserChangeEmailRequest) GetAuth() *UserTokenRequest {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *UserChangeEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserChangeEmailResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VerificationCode string                 `protobuf:"bytes,1,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	CodeExpires      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=code_expires,json=codeExpires,proto3" json:"code_expires,omitempty"`
	Status           uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserChangeEmailResponse) Reset() {
	*x = UserChangeEmailResponse{}
	mi := &file_server_user_pb_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChangeEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChangeEmailResponse) ProtoMessage() {}

func (x *UserChangeEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_user_pb_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChangeEmailResponse.ProtoReflect.Descriptor instead.
func (*UserChangeEmailResponse) Descriptor() ([]byte, []int) {
	return file_server_user_pb_user_proto_rawDescGZIP(), []int{25}
}

func (x *UserChangeEmailResponse) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *UserChangeEmailResponse) GetCodeExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.CodeExpires
	}
	return nil
}

func (x *UserChangeEmailResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_server_user_pb_user_proto protoreflect.FileDescriptor

const file_server_user_pb_user_proto_rawDesc = "" +
	"\n" +
	"\x19server/user-pb/user.proto\x12\auser_pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfe\x01\n" +
	"\vUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprofile_pic\x18\x03 \x01(\tR\n" +
	"profilePic\x12\x1c\n" +
	"\tvalidated\x18\x04 \x01(\bR\tvalidated\x12\x14\n" +
	"\x05admin\x18\x05 \x01(\bR\x05admin\x12\x1f\n" +
	"\vsuper_admin\x18\x06 \x01(\bR\n" +
	"superAdmin\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12;\n" +
	"\vcode_expire\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"codeExpire\"\xc3\x02\n" +
	"\x10UserLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\abrowser\x18\x02 \x01(\tR\abrowser\x12'\n" +
	"\x0fbrowser_version\x18\x03 \x01(\tR\x0ebrowserVersion\x12)\n" +
	"\x10operating_system\x18\x04 \x01(\tR\x0foperatingSystem\x128\n" +
	"\x18operating_system_version\x18\x05 \x01(\tR\x16operatingSystemVersion\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\tR\x03cpu\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12'\n" +
	"\x0fcookies_enabled\x18\t \x01(\bR\x0ecookiesEnabled\"'\n" +
	"\x0fUserMailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xc3\x02\n" +
	"\x10UserTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\abrowser\x18\x02 \x01(\tR\abrowser\x12'\n" +
	"\x0fbrowser_version\x18\x03 \x01(\tR\x0ebrowserVersion\x12)\n" +
	"\x10operating_system\x18\x04 \x01(\tR\x0foperatingSystem\x128\n" +
	"\x18operating_system_version\x18\x05 \x01(\tR\x16operatingSystemVersion\x12\x10\n" +
	"\x03cpu\x18\x06 \x01(\tR\x03cpu\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12'\n" +
	"\x0fcookies_enabled\x18\t \x01(\bR\x0ecookiesEnabled\"\x1f\n" +
	"\rUserIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"K\n" +
	"\x11UserDeleteRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12 \n" +
	"\vpermanently\x18\x02 \x01(\bR\vpermanently\"v\n" +
	"\x11UserUpdateRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprofile_pic\x18\x03 \x01(\tR\n" +
	"profilePic\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\"8\n" +
	"\x0eUserIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\",\n" +
	"\x12UserStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\"@\n" +
	"\x11ListUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.user_pb.UserResponseR\x05users\"\xc6\x02\n" +
	"\fUserResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprofile_pic\x18\x03 \x01(\tR\n" +
	"profilePic\x12\x1c\n" +
	"\tvalidated\x18\x04 \x01(\bR\tvalidated\x12\x14\n" +
	"\x05admin\x18\x05 \x01(\bR\x05admin\x12\x1f\n" +
	"\vsuper_admin\x18\x06 \x01(\bR\n" +
	"superAdmin\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\x12;\n" +
	"\vcode_expire\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"codeExpire\x12\x16\n" +
	"\x06bucket\x18\t \x01(\tR\x06bucket\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\v \x01(\tR\tphoneE164\")\n" +
	"\x13UserValidateRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"?\n" +
	"\x11UserLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\"\x8d\x02\n" +
	"\x11UserTokenResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12#\n" +
	"\rtoken_refresh\x18\x04 \x01(\tR\ftokenRefresh\x12N\n" +
	"\x15token_refresh_expires\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x13tokenRefreshExpires\x12?\n" +
	"\rtoken_expires\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ftokenExpires\"D\n" +
	"\x16UpdateUserAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05admin\x18\x02 \x01(\bR\x05admin\"\x8a\x03\n" +
	"\x1cUserLoginWithPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\abrowser\x18\x03 \x01(\tR\abrowser\x12'\n" +
	"\x0fbrowser_version\x18\x04 \x01(\tR\x0ebrowserVersion\x12)\n" +
	"\x10operating_system\x18\x05 \x01(\tR\x0foperatingSystem\x128\n" +
	"\x18operating_system_version\x18\x06 \x01(\tR\x16operatingSystemVersion\x12\x10\n" +
	"\x03cpu\x18\a \x01(\tR\x03cpu\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12\x1a\n" +
	"\btimezone\x18\t \x01(\tR\btimezone\x12'\n" +
	"\x0fcookies_enabled\x18\n" +
	" \x01(\bR\x0ecookiesEnabled\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\v \x01(\tR\tphoneE164\"\xa1\x03\n" +
	"\x1fUserRegisterWithPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\abrowser\x18\x04 \x01(\tR\abrowser\x12'\n" +
	"\x0fbrowser_version\x18\x05 \x01(\tR\x0ebrowserVersion\x12)\n" +
	"\x10operating_system\x18\x06 \x01(\tR\x0foperatingSystem\x128\n" +
	"\x18operating_system_version\x18\a \x01(\tR\x16operatingSystemVersion\x12\x10\n" +
	"\x03cpu\x18\b \x01(\tR\x03cpu\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\x12\x1a\n" +
	"\btimezone\x18\n" +
	" \x01(\tR\btimezone\x12'\n" +
	"\x0fcookies_enabled\x18\v \x01(\bR\x0ecookiesEnabled\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\f \x01(\tR\tphoneE164\"\xbf\x01\n" +
	" UserRegisterWithPasswordResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\x12=\n" +
	"\fcode_expires\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcodeExpires\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\"7\n" +
	"\x1fUserRequestPasswordResetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x96\x01\n" +
	" UserRequestPasswordResetResponse\x12\x1f\n" +
	"\vreset_token\x18\x01 \x01(\tR\n" +
	"resetToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\"^\n" +
	"\x18UserResetPasswordRequest\x12\x1f\n" +
	"\vreset_token\x18\x01 \x01(\tR\n" +
	"resetToken\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"3\n" +
	"\x19UserResetPasswordResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\"c\n" +
	"\x13UserSetPhoneRequest\x12-\n" +
	"\x04auth\x18\x01 \x01(\v2\x19.user_pb.UserTokenRequestR\x04auth\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x02 \x01(\tR\tphoneE164\"\x98\x01\n" +
	"\x19UserChangePasswordRequest\x12-\n" +
	"\x04auth\x18\x01 \x01(\v2\x19.user_pb.UserTokenRequestR\x04auth\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"]\n" +
	"\x16UserChangeEmailRequest\x12-\n" +
	"\x04auth\x18\x01 \x01(\v2\x19.user_pb.UserTokenRequestR\x04auth\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\x9d\x01\n" +
	"\x17UserChangeEmailResponse\x12+\n" +
	"\x11verification_code\x18\x01 \x01(\tR\x10verificationCode\x12=\n" +
	"\fcode_expires\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcodeExpires\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status2\xb3\f\n" +
	"\x04User\x129\n" +
	"\x06Create\x12\x14.user_pb.UserRequest\x1a\x17.user_pb.UserIDResponse\"\x00\x126\n" +
	"\x03Get\x12\x16.user_pb.UserIDRequest\x1a\x15.user_pb.UserResponse\"\x00\x12C\n" +
	"\x06Update\x12\x1a.user_pb.UserUpdateRequest\x1a\x1b.user_pb.UserStatusResponse\"\x00\x12C\n" +
	"\x06Delete\x12\x1a.user_pb.UserDeleteRequest\x1a\x1b.user_pb.UserStatusResponse\"\x00\x12<\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x1a.user_pb.ListUsersResponse\"\x00\x12@\n" +
	"\x05Login\x12\x19.user_pb.UserLoginRequest\x1a\x1a.user_pb.UserLoginResponse\"\x00\x12X\n" +
	"\x11LoginWithPassword\x12%.user_pb.UserLoginWithPasswordRequest\x1a\x1a.user_pb.UserTokenResponse\"\x00\x12m\n" +
	"\x14RegisterWithPassword\x12(.user_pb.UserRegisterWithPasswordRequest\x1a).user_pb.UserRegisterWithPasswordResponse\"\x00\x12m\n" +
	"\x14RequestPasswordReset\x12(.user_pb.UserRequestPasswordResetRequest\x1a).user_pb.UserRequestPasswordResetResponse\"\x00\x12X\n" +
	"\rResetPassword\x12!.user_pb.UserResetPasswordRequest\x1a\".user_pb.UserResetPasswordResponse\"\x00\x12A\n" +
	"\bSetPhone\x12\x1c.user_pb.UserSetPhoneRequest\x1a\x15.user_pb.UserResponse\"\x00\x12S\n" +
	"\x0eChangePassword\x12\".user_pb.UserChangePasswordRequest\x1a\x1b.user_pb.UserStatusResponse\"\x00\x12R\n" +
	"\vChangeEmail\x12\x1f.user_pb.UserChangeEmailRequest\x1a .user_pb.UserChangeEmailResponse\"\x00\x12A\n" +
	"\x06LogOut\x12\x18.user_pb.UserMailRequest\x1a\x1b.user_pb.UserStatusResponse\"\x00\x12F\n" +
	"\bValidate\x12\x1c.user_pb.UserValidateRequest\x1a\x1a.user_pb.UserTokenResponse\"\x00\x12C\n" +
	"\n" +
	"VerifyUser\x12\x16.user_pb.UserIDRequest\x1a\x1b.user_pb.UserStatusResponse\"\x00\x12?\n" +
	"\n" +
	"GetByEmail\x12\x18.user_pb.UserMailRequest\x1a\x15.user_pb.UserResponse\"\x00\x12A\n" +
	"\vTokenToUser\x12\x19.user_pb.UserTokenRequest\x1a\x15.user_pb.UserResponse\"\x00\x12?\n" +
	"\x06Health\x12\x16.user_pb.UserIDRequest\x1a\x1b.user_pb.UserStatusResponse\"\x00\x12W\n" +
	"\x15UpdateUserAdminStatus\x12\x1f.user_pb.UpdateUserAdminRequest\x1a\x1b.user_pb.UserStatusResponse\"\x00\x12B\n" +
	"\aRefresh\x12\x19.user_pb.UserTokenRequest\x1a\x1a.user_pb.UserTokenResponse\"\x00B6Z4github.com/BaukunstPatrimonio/user-go/server/user-pbb\x06proto3"

var (
	file_server_user_pb_user_proto_rawDescOnce sync.Once
	file_server_user_pb_user_proto_rawDescData []byte
)

func file_server_user_pb_user_proto_rawDescGZIP() []byte {
	file_server_user_pb_user_proto_rawDescOnce.Do(func() {
		file_server_user_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_user_pb_user_proto_rawDesc), len(file_server_user_pb_user_proto_rawDesc)))
	})
	return file_server_user_pb_user_proto_rawDescData
}

var file_server_user_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_server_user_pb_user_proto_goTypes = []any{
	(*UserRequest)(nil),                      // 0: user_pb.UserRequest
	(*UserLoginRequest)(nil),                 // 1: user_pb.UserLoginRequest
	(*UserMailRequest)(nil),                  // 2: user_pb.UserMailRequest
	(*UserTokenRequest)(nil),                 // 3: user_pb.UserTokenRequest
	(*UserIDRequest)(nil),                    // 4: user_pb.UserIDRequest
	(*UserDeleteRequest)(nil),                // 5: user_pb.UserDeleteRequest
	(*UserUpdateRequest)(nil),                // 6: user_pb.UserUpdateRequest
	(*UserIDResponse)(nil),                   // 7: user_pb.UserIDResponse
	(*UserStatusResponse)(nil),               // 8: user_pb.UserStatusResponse
	(*ListUsersResponse)(nil),                // 9: user_pb.ListUsersResponse
	(*UserResponse)(nil),                     // 10: user_pb.UserResponse
	(*UserValidateRequest)(nil),              // 11: user_pb.UserValidateRequest
	(*UserLoginResponse)(nil),                // 12: user_pb.UserLoginResponse
	(*UserTokenResponse)(nil),                // 13: user_pb.UserTokenResponse
	(*UpdateUserAdminRequest)(nil),           // 14: user_pb.UpdateUserAdminRequest
	(*UserLoginWithPasswordRequest)(nil),     // 15: user_pb.UserLoginWithPasswordRequest
	(*UserRegisterWithPasswordRequest)(nil),  // 16: user_pb.UserRegisterWithPasswordRequest
	(*UserRegisterWithPasswordResponse)(nil), // 17: user_pb.UserRegisterWithPasswordResponse
	(*UserRequestPasswordResetRequest)(nil),  // 18: user_pb.UserRequestPasswordResetRequest
	(*UserRequestPasswordResetResponse)(nil), // 19: user_pb.UserRequestPasswordResetResponse
	(*UserResetPasswordRequest)(nil),         // 20: user_pb.UserResetPasswordRequest
	(*UserResetPasswordResponse)(nil),        // 21: user_pb.UserResetPasswordResponse
	(*UserSetPhoneRequest)(nil),              // 22: user_pb.UserSetPhoneRequest
	(*UserChangePasswordRequest)(nil),        // 23: user_pb.UserChangePasswordRequest
	(*UserChangeEmailRequest)(nil),           // 24: user_pb.UserChangeEmailRequest
	(*UserChangeEmailResponse)(nil),          // 25: user_pb.UserChangeEmailResponse
	(*timestamppb.Timestamp)(nil),            // 26: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 27: google.protobuf.Empty
}
var file_server_user_pb_user_proto_depIdxs = []int32{
	26, // 0: user_pb.UserRequest.code_expire:type_name -> google.protobuf.Timestamp
	10, // 1: user_pb.ListUsersResponse.users:type_name -> user_pb.UserResponse
	26, // 2: user_pb.UserResponse.code_expire:type_name -> google.protobuf.Timestamp
	26, // 3: user_pb.UserTokenResponse.token_refresh_expires:type_name -> google.protobuf.Timestamp
	26, // 4: user_pb.UserTokenResponse.token_expires:type_name -> google.protobuf.Timestamp
	26, // 5: user_pb.UserRegisterWithPasswordResponse.code_expires:type_name -> google.protobuf.Timestamp
	26, // 6: user_pb.UserRequestPasswordResetResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 7: user_pb.UserSetPhoneRequest.auth:type_name -> user_pb.UserTokenRequest
	3,  // 8: user_pb.UserChangePasswordRequest.auth:type_name -> user_pb.UserTokenRequest
	3,  // 9: user_pb.UserChangeEmailRequest.auth:type_name -> user_pb.UserTokenRequest
	26, // 10: user_pb.UserChangeEmailResponse.code_expires:type_name -> google.protobuf.Timestamp
	0,  // 11: user_pb.User.Create:input_type -> user_pb.UserRequest
	4,  // 12: user_pb.User.Get:input_type -> user_pb.UserIDRequest
	6,  // 13: user_pb.User.Update:input_type -> user_pb.UserUpdateRequest
	5,  // 14: user_pb.User.Delete:input_type -> user_pb.UserDeleteRequest
	27, // 15: user_pb.User.List:input_type -> google.protobuf.Empty
	1,  // 16: user_pb.User.Login:input_type -> user_pb.UserLoginRequest
	15, // 17: user_pb.User.LoginWithPassword:input_type -> user_pb.UserLoginWithPasswordRequest
	16, // 18: user_pb.User.RegisterWithPassword:input_type -> user_pb.UserRegisterWithPasswordRequest
	18, // 19: user_pb.User.RequestPasswordReset:input_type -> user_pb.UserRequestPasswordResetRequest
	20, // 20: user_pb.User.ResetPassword:input_type -> user_pb.UserResetPasswordRequest
	22, // 21: user_pb.User.SetPhone:input_type -> user_pb.UserSetPhoneRequest
	23, // 22: user_pb.User.ChangePassword:input_type -> user_pb.UserChangePasswordRequest
	24, // 23: user_pb.User.ChangeEmail:input_type -> user_pb.UserChangeEmailRequest
	2,  // 24: user_pb.User.LogOut:input_type -> user_pb.UserMailRequest
	11, // 25: user_pb.User.Validate:input_type -> user_pb.UserValidateRequest
	4,  // 26: user_pb.User.VerifyUser:input_type -> user_pb.UserIDRequest
	2,  // 27: user_pb.User.GetByEmail:input_type -> user_pb.UserMailRequest
	3,  // 28: user_pb.User.TokenToUser:input_type -> user_pb.UserTokenRequest
	4,  // 29: user_pb.User.Health:input_type -> user_pb.UserIDRequest
	14, // 30: user_pb.User.UpdateUserAdminStatus:input_type -> user_pb.UpdateUserAdminRequest
	3,  // 31: user_pb.User.Refresh:input_type -> user_pb.UserTokenRequest
	7,  // 32: user_pb.User.Create:output_type -> user_pb.UserIDResponse
	10, // 33: user_pb.User.Get:output_type -> user_pb.UserResponse
	8,  // 34: user_pb.User.Update:output_type -> user_pb.UserStatusResponse
	8,  // 35: user_pb.User.Delete:output_type -> user_pb.UserStatusResponse
	9,  // 36: user_pb.User.List:output_type -> user_pb.ListUsersResponse
	12, // 37: user_pb.User.Login:output_type -> user_pb.UserLoginResponse
	13, // 38: user_pb.User.LoginWithPassword:output_type -> user_pb.UserTokenResponse
	17, // 39: user_pb.User.RegisterWithPassword:output_type -> user_pb.UserRegisterWithPasswordResponse
	19, // 40: user_pb.User.RequestPasswordReset:output_type -> user_pb.UserRequestPasswordResetResponse
	21, // 41: user_pb.User.ResetPassword:output_type -> user_pb.UserResetPasswordResponse
	10, // 42: user_pb.User.SetPhone:output_type -> user_pb.UserResponse
	8,  // 43: user_pb.User.ChangePassword:output_type -> user_pb.UserStatusResponse
	25, // 44: user_pb.User.ChangeEmail:output_type -> user_pb.UserChangeEmailResponse
	8,  // 45: user_pb.User.LogOut:output_type -> user_pb.UserStatusResponse
	13, // 46: user_pb.User.Validate:output_type -> user_pb.UserTokenResponse
	8,  // 47: user_pb.User.VerifyUser:output_type -> user_pb.UserStatusResponse
	10, // 48: user_pb.User.GetByEmail:output_type -> user_pb.UserResponse
	10, // 49: user_pb.User.TokenToUser:output_type -> user_pb.UserResponse
	8,  // 50: user_pb.User.Health:output_type -> user_pb.UserStatusResponse
	8,  // 51: user_pb.User.UpdateUserAdminStatus:output_type -> user_pb.UserStatusResponse
	13, // 52: user_pb.User.Refresh:output_type -> user_pb.UserTokenResponse
	32, // [32:53] is the sub-list for method output_type
	11, // [11:32] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_server_user_pb_user_proto_init() }
func file_server_user_pb_user_proto_init() {
	if File_server_user_pb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_user_pb_user_proto_rawDesc), len(file_server_user_pb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_user_pb_user_proto_goTypes,
		DependencyIndexes: file_server_user_pb_user_proto_depIdxs,
		MessageInfos:      file_server_user_pb_user_proto_msgTypes,
	}.Build()
	File_server_user_pb_user_proto = out.File
	file_server_user_pb_user_proto_goTypes = nil
	file_server_user_pb_user_proto_depIdxs = nil
}
