package models

import "errors"

var (
	ErrUserNotFound              = errors.New("user not found")
	ErrUserNotAuthenticated      = errors.New("user not authenticated")
	ErrInvalidCode               = errors.New("code is invalid")
	ErrExpiredCode               = errors.New("code is expired")
	ErrUserNotLogged             = errors.New("user not logged")
	ErrInvalidUser               = errors.New("invalid user")
	ErrSecurityMismatch          = errors.New("security data user's token don't match")
	ErrInvalidSignature          = errors.New("invalid signature token")
	ErrTokenExpired              = errors.New("token expired")
	ErrParsingToken              = errors.New("error parsing token")
	ErrInvalidToken              = errors.New("invalid token")
	ErrSessionDeviceMismatch     = errors.New("session device mismatch")
	ErrInvalidCredentials        = errors.New("invalid email or password")
	ErrCurrentPasswordInvalid    = errors.New("current password is invalid")
	ErrCredentialNotFound        = errors.New("password credential not found")
	ErrAccountNotValidated       = errors.New("account is not validated")
	ErrUserAlreadyExists         = errors.New("user already exists")
	ErrInvalidPassword           = errors.New("password does not meet registration requirements")
	ErrPasswordResetUnavailable  = errors.New("password reset is unavailable")
	ErrInvalidPasswordResetToken = errors.New("password reset token is invalid or expired")
	ErrInvalidPhone              = errors.New("phone must be a canonical E.164 number")
	ErrPhoneAlreadyExists        = errors.New("phone identity already exists")
	ErrInvalidLoginIdentity      = errors.New("provide exactly one password login identity")
	ErrExistingAccountNotReady   = errors.New("existing account is not validated")
)
