name: Deploy API Prod

on:
  push:
    branches: [ "prod" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set date tag
      run: |
        echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_ENV"
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io/alvarotor
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ghcr.io/alvarotor/user-go:prod-latest
          ghcr.io/alvarotor/user-go:prod-${{ env.TAG }}
