name: Deploy API Dev 

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set date tag
      run: |
        echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_ENV"
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io/alvarotor
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ghcr.io/alvarotor/user-go:dev-latest
          ghcr.io/alvarotor/user-go:dev-${{ env.TAG }}

    - name: REST API to update container
      run: |
        curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" https://watchtower.partypanther.net/v1/update?image=ghcr.io/alvarotor/user-go,dev-latest --max-time 40
